### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by riseremi** [Kode/vscode-kha-extension-pack#1]
## Overview
I'm trying to "debug and run" a clean project generated by "Kha: Init project" command. Build fails both for HTML5 and Krom targets. Here's the output:
```bash
> Executing task: node C:\Users\Remi\.vscode\extensions\kodetech.kha-20.1.0\Kha\make.js debug-html5 --debug <

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\Remi\Documents\GitHub\kha-test\UsersRemi.vscodeextensionskodetech.kha-20.1.0Khamake.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
The terminal process terminated with exit code: 1
```

Interesting part here is the path to khamake:
`C:\Users\Remi\Documents\GitHub\kha-test\UsersRemi.vscodeextensionskodetech.kha-20.1.0Khamake.js`

Slashes are missing for some reason.

## Environment Info
OS: Windows 10 Pro 1903, build 18362.535
VS Code: 1.41.1
Kha Extension Pack: 20.1.0
Haxe: 4.0.5

**Comment by riseremi** [comment]
Sorry, wrong repo. Recreated here: https://github.com/Kode/vscode-kha/issues/19
